/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;



/**
 *
 * @author wazzp
 */
public class JanCardapio extends javax.swing.JFrame {
    String[] carregarSabores(){
        String[] str = new String[PizzaNet.sabores.size()];
        for(int i=0;i<PizzaNet.sabores.size();i++){
            str[i] = PizzaNet.sabores.get(i).getNome();
        }
        return str;
    }
    String[] carregarIngredientes(){
        String[] str = new String[PizzaNet.ingredientes.size()];
        for(int i=0;i<PizzaNet.ingredientes.size();i++){
            str[i] = PizzaNet.ingredientes.get(i).getDescricao();
        }
        return str;
    }
    /**
     * Creates new form JanCardapio
     */
    public JanCardapio() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSabores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSabores = new javax.swing.JList<>();
        lblIngredientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listIngred = new javax.swing.JList<>();
        btIncluirSabor = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btMostrarSab = new javax.swing.JButton();
        btMostrarSel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSabores.setText("Sabores");

        listSabores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = carregarSabores();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listSabores);

        lblIngredientes.setText("Ingredientes");

        listIngred.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = carregarIngredientes();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listIngred);

        btIncluirSabor.setText("Incluir sabor");

        btExcluir.setText("Excluir Sabor");

        btAlterar.setText("Alterar Sabor");

        btMostrarSab.setText("Mostrar todos");
        btMostrarSab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarSabActionPerformed(evt);
            }
        });

        btMostrarSel.setText("Mostrar Selecionado");
        btMostrarSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarSelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSabores)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btIncluirSabor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblIngredientes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btMostrarSel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btMostrarSab, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngredientes)
                    .addComponent(lblSabores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btExcluir)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btIncluirSabor)
                        .addComponent(btMostrarSel)
                        .addComponent(btMostrarSab)
                        .addComponent(btAlterar)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMostrarSabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarSabActionPerformed
        // TODO add your handling code here:
        listIngred.setModel(new javax.swing.AbstractListModel<String>() {
                                String[] strings = carregarIngredientes();
                                public int getSize() { return strings.length; }
                                public String getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_btMostrarSabActionPerformed

    private void btMostrarSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarSelActionPerformed
        // TODO add your handling code here:
        int i=0,l=0, idSbrSelecionado = PizzaNet.sabores.get(listSabores.getSelectedIndex()).getIdSabor();
        ArrayList<String> str = new ArrayList<>();
        for(i=0;i<PizzaNet.sab_ingr.size();i++){
            if(PizzaNet.sab_ingr.get(i).getSaborID()==idSbrSelecionado){
                System.out.println(PizzaNet.sab_ingr.get(i).getIngID());
                for(int j=0;j<PizzaNet.ingredientes.size();j++){
                    if(PizzaNet.ingredientes.get(j).getIdIngrediente()==PizzaNet.sab_ingr.get(i).getIngID())
                        str.add(PizzaNet.ingredientes.get(j).getDescricao());   
                }
            }
        }
        String[] str2 = new String[str.size()];
        for(i=0;i<str.size();i++){
            str2[i] = str.get(i);
        }
        
        listIngred.setModel(new javax.swing.AbstractListModel<String>() {
                                String[] strings = str2;
                                public int getSize() { return strings.length; }
                                public String getElementAt(int i) { return strings[i]; }
        });
        //Muito mais facil fazer um query     
    }//GEN-LAST:event_btMostrarSelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanCardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JanCardapio().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btIncluirSabor;
    private javax.swing.JButton btMostrarSab;
    private javax.swing.JButton btMostrarSel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIngredientes;
    private javax.swing.JLabel lblSabores;
    private javax.swing.JList<String> listIngred;
    private javax.swing.JList<String> listSabores;
    // End of variables declaration//GEN-END:variables
}
